# Utiliser une image de base officielle de Python
FROM python:3.12-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier de dépendances dans le conteneur
COPY requirements.txt requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le contenu du répertoire actuel dans le répertoire de travail du conteneur
COPY . .

# Définir la variable d'environnement pour désactiver le buffering de sortie
ENV PYTHONUNBUFFERED=1

#  port sur lequel l'application va écouter
EXPOSE 8000

# Commande à exécuter au démarrage du conteneur
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
