# Utiliser une image de base
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier de dépendances dans le conteneur
COPY docker/requirements.txt requirements.txt

# Installer les dépendances
RUN pip install -r requirements.txt

# Copier le reste de l'application
COPY . .

# Exposer le port de l'application
EXPOSE 8000

# Démarrer l'application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
